* gnetlist.exe -g spice-sdb -O jsim -O param -O sort_mode -v -o ./js/test_and2t_changed.js C:\Program Files (x86)\gEDA\test_and2t_changed.sch
*********************************************************
* Spice file generated by gnetlist                      *
* spice-sdb version 4.28.2007 by SDB --                 *
* provides advanced spice netlisting capability.        *
* Documentation at http://www.brorson.com/gEDA/SPICE/   *
*********************************************************
*vvvvvvvv  Included SPICE model from ./js/mitll_ptlrx.js vvvvvvvv
******************************************
* Begin .SUBCKT model                    *
* spice-sdb ver 4.28.2007                *
*                                        *
* RSFQ generic cell for MITLL sfq5ee     *
* Seedling project under IARPA-BAA-14-03 *
* Authored 1 March 2016, JA Delport, SU  *
* Last mod 16 Oct 2016, CJ Fourie, SU    *
*   (Optimized)                          *
******************************************
.SUBCKT MITLL_PTLRX 2 6 
*==============  Begin SPICE netlist of main design ============
B01        1          9          jmitll     area=1
B02        4          8          jmitll     area=1
B03        5          7          jmitll     area=1
IB01       0          10         pwl(0      0 5p 155u)
L01        2          1          0.2p      
L02        1          3          4.3p      
L03        3          4          4.6p      
L04        4          5          5.0p      
L05        5          6          2.3p      
LP01       0          9          0.34p     
LP02       0          8          0.06p     
LP03       0          7          0.03p     
LPR01      3          10         0.2p      
LRB01      9          11         0.5p      
LRB02      8          12         1p        
LRB03      7          13         1p        
RB01       11         1          9.7       
RB02       12         4          9.7       
RB03       13         5          9.7       
.model jmitll jj(rtype=1, vg=2.8mV, cap=0.07pF, r0=160ohm, rn=16ohm, icrit=0.1mA)
.ends MITLL_PTLRX
*******************************
*^^^^^^^^  End of included SPICE model from ./js/mitll_ptlrx.js ^^^^^^^^
*
*vvvvvvvv  Included SPICE model from ./js/mitll_dcsfq.js vvvvvvvv
*****************************************
* Begin .SUBCKT model                   *
* spice-sdb ver 4.28.2007               *
*                                       * 
* RSFQ generic cell for MITLL sfq5ee    *
* Authored 3 Nov 2015, CJ Fourie, SU    *
*****************************************
.SUBCKT mitll_dcsfq 8 11 
*==============  Begin SPICE netlist of main design ============
B1         1          2          jjmitll100 area=2.25
B2         3          4          jjmitll100 area=2.25
B3         5          6          jjmitll100 area=2.5
IB1        0          2          pwl(0      0 5p 275uA)
IB2        0          5          pwl(0      0 5p 175uA)
L1         8          7          1p        
L2         7          0          3.9p      
L3         7          1          0.6p      
L4         2          3          1.1p      
L5         3          5          4.5p      
L6         5          11         2p        
Lp2        4          0          0.2p      
Lp3        6          0          0.2p      
LRB1       9          2          1p        
LRB2       10         4          1p        
LRB3       12         6          1p        
RB1        1          9          4.31      
RB2        3          10         4.31      
RB3        5          12         3.88      
.model jjmitll100 jj(rtype=1, vg=2.8mV, cap=0.07pF, r0=160, rn=16, icrit=0.1mA)
.ends mitll_dcsfq
*******************************
*^^^^^^^^  End of included SPICE model from ./js/mitll_dcsfq.js ^^^^^^^^
*
*vvvvvvvv  Included SPICE model from ./js/mitll_ptltx.js vvvvvvvv
******************************************
* Begin .SUBCKT model                    *
* spice-sdb ver 4.28.2007                *
*                                        *
* RSFQ generic cell for MITLL sfq5ee     *
* Seedling project under IARPA-BAA-14-03 *
* Authored 1 March 2016, JA Delport, SU  *
* Last mod 16 Oct 2016, CJ Fourie, SU    *
*   (Optimized)                          *
******************************************
.SUBCKT MITLL_PTLTX 1 2 
*==============  Begin SPICE netlist of main design ============
B01        3          7          jmitll     area=2
B02        4          6          jmitll     area=1.62
IB01       0          10         pwl(0      0 5p 230u)
IB02       0          11         pwl(0      0 5p 82u)
L01        1          3          2.5p      
L02        3          4          3.3p      
L03        4          5          0.35p     
LP01       0          7          0.05p     
LP02       0          6          0.12p     
LPR01      3          10         0.2p      
LPR02      4          11         1.3p      
LRB01      7          8          1p        
LRB02      6          9          1p        
RB01       8          3          4.85      
RB02       9          4          6.3       
RINS       5          2          1.36      
.model jmitll jj(rtype=1, vg=2.8mV, cap=0.07pF, r0=160ohm, rn=16ohm, icrit=0.1mA)
.ends MITLL_PTLTX
*******************************
*^^^^^^^^  End of included SPICE model from ./js/mitll_ptltx.js ^^^^^^^^
*
*==============  Begin SPICE netlist of main design ============
B01        36         40         jmitll     area=1.31899
B01_rx1    6          8          jmitll     area=0.4
B01_rx2    11         13         jmitll     area=0.88063
B01_rx3    28         30         jmitll     area=0.88063
B01_tx1    16         20         jmitll     area=2.26625
B02        63         67         jmitll     area=1.31899
B03        37         48         jmitll     area=1.13403
B04        68         64         jmitll     area=1.13403
B05        49         50         jmitll     area=1.52701
B06        50         69         jmitll     area=1.52701
B07        51         52         jmitll     area=1.25725
B08        43         47         jmitll     area=1.56701
B09        54         55         jmitll     area=2.03545
B10        34         39         jmitll     area=1.75934
B11        61         66         jmitll     area=1.75934
B14        41         46         jmitll     area=1.50181
IA         0          26         pwl(0      0 30p 0 33p 600u 36p 0 45p 0 48p 600u 51p 0 166p 0 169p 600u 172p 0)
IB         0          3          pwl(0      0 160p 0 163p 600u 166p 0 200p 0 203p 600u 206p 0 220p 0 223p 600u 226p 0)
IB01       0          38         pwl(0      0 5p 0.000113269)
IB01_rx1   0          9          pwl(0      0 5p 0.00012754)
IB01_rx2   0          14         pwl(0      0 5p 0.000131447)
IB01_rx3   0          31         pwl(0      0 5p 0.000131447)
IB01_tx1   0          22         pwl(0      0 5p 0.000213665)
IB02       0          65         pwl(0      0 5p 0.000113269)
IB03       0          56         pwl(0      0 5p 6.26758e-005)
IB07       0          45         pwl(0      0 5p 0.000179299)
ICLK       0          1          pulse(0    600u 10p 2p 2p 1p 50p)
L01        37         49         2.57965e-012    
L01_rx3    7          6          1.7746e-012
L01_rx2    12         11         1.53695e-012
L01_rx1    29         28         1.53695e-012
L01_tx1    54         16         4.64399e-012
L02        69         64         2.57965e-012    
L02_tx1    16         18         2.74282e-012
L03        34         35         1.93254e-012    
L04        61         62         1.93254e-012    
L05        44         48         1.14641e-012    
L06        68         44         1.14641e-012    
L07        42         43         1.99319e-012    
L08        51         53         3.9e-014    
L09        53         54         2.92475e-012    
L13        28         34         2.2304e-012    
L14        11         61         2.2304e-012    
L15        35         36         6.1049e-012    
L16        62         63         6.1049e-012    
L17        6          41         1.94279e-012    
L19        41         42         2.03734e-013    
L20        50         51         3.9901e-013    
L21        36         37         1.29089e-013    
L22        63         64         1.29089e-013    
L23        43         44         1e-014    
LP01       0          40         2.55e-013   
LP01_rx1   0          8          3.4e-013
LP01_rx2   0          13         3.4e-013
LP01_rx3   0          30         3.4e-013
LP01_tx1   0          20         5e-014
LP02       0          67         2.55e-013   
LP07       0          52         2.99e-013   
LP08       0          47         2.11e-013   
LP09       0          55         1.74e-013   
LP10       0          39         2.21e-013   
LP11       0          66         2.21e-013   
LP14       0          46         1.87e-013   
LPR01_rx1  6          9          2e-013
LPR01_rx2  11         14         2e-013
LPR01_rx3  28         31         2e-013
LPR01_tx1  16         22         2e-013
LPR1       35         38         1.3e-014   
LPR2       62         65         1.3e-014   
LPR3       53         56         1.901e-012   
LPR4       42         45         8.5e-013   
LRB01      58         0          3.1385e-012  
LRB01_rx1  0          10         9.88961e-012
LRB01_rx2  0          15         4.60122e-012
LRB01_rx3  0          32         4.60122e-012
LRB01_tx1  0          21         1.91024e-012
LRB02      71         0          3.1385e-012  
LRB03      59         48         3.61777e-012  
LRB04      68         72         3.61777e-012  
LRB05      60         50         2.73819e-012  
LRB06      50         75         2.73819e-012  
LRB07      76         0          3.28281e-012  
LRB08      74         0          2.6734e-012  
LRB09      77         0          2.10417e-012  
LRB10      57         0          2.40301e-012  
LRB11      70         0          2.40301e-012  
LRB14      73         0          2.78079e-012  
RB01       58         36         5.20089   
RB01_rx1   10         6          17.1498
RB01_rx2   15         11         7.78977
RB01_rx3   32         28         7.78977
RB01_tx1   21         16         3.02698
RB02       71         63         5.20089   
RB03       59         37         6.04915   
RB04       64         72         6.04915   
RB05       60         49         4.49237   
RB06       69         75         4.49237   
RB07       76         51         5.4563   
RB08       74         43         4.3777   
RB09       77         54         3.37022   
RB10       57         34         3.89913   
RB11       70         61         3.89913   
RB14       73         41         4.56777   
RINS_tx1   18         19         1.36      
ROUT       5          0          2         
RINS_clk   170		  7          6.32
T_in_clk   23         0          170          0 LOSSLESS Z0=5 TD=10p
T_in_in    24         0          12         0 LOSSLESS Z0=5 TD=10p
T_in_in2   33         0          29         0 LOSSLESS Z0=5 TD=10p
T_out      19         0          25         0 LOSSLESS Z0=5 TD=10p
X_rx       MITLL_PTLRX 25         5         
X_tx1      MITLL_PTLTX 2          23        
X_tx2      MITLL_PTLTX 4          24        
X_tx3      MITLL_PTLTX 27         33        
XDCSFQCLK  MITLL_DCSFQ 1          2         
XDCSFQIN   MITLL_DCSFQ 3          4         
XDCSFQIN2  MITLL_DCSFQ 26         27        
.model jmitll jj(rtype=1, vg=2.6mV, cap=0.07pF, r0=160, rn=16, icrit=0.1mA)
.tran 0.25p 500p 0 0.25p
*.print phase B07
*.print DEVI L16
*.print DEVI L22
.print DEVI L01_rx1
.print DEVI L01_rx2
.print DEVI L01_rx3
.print DEVI L02_tx1
*.print DEVI ROUT
.print phase B01       
.print phase B02
.print phase B03 
.print phase B04
.print phase B05
.print phase B06
.print phase B07
.print phase B08
.print phase B09
.print phase B10
.print phase B11
.print phase B14 
*.print phase X_rx_B03
.end
