* gnetlist.exe -g spice-sdb -O jsim -O param -O sort_mode -v -o ./js/2bitadder.js C:\Program Files (x86)\gEDA\2bitadder.sch
*********************************************************
* Spice file generated by gnetlist                      *
* spice-sdb version 4.28.2007 by SDB --                 *
* provides advanced spice netlisting capability.        *
* Documentation at http://www.brorson.com/gEDA/SPICE/   *
*********************************************************
*vvvvvvvv  Included SPICE model from ./js/mitll_and2t.js vvvvvvvv
*****************************************
* Begin .SUBCKT model                    *
* spice-sdb ver 4.28.2007                *
*                                        *
* RSFQ generic cell for MITLL sfq5ee     *
* Project under IARPA-BAA-16-03          *
* Authored 1 March 2016, JA Delport, SU  *
* Modified 9 Oct 2016, CJ Fourie, SU     *
*   (optmized)                           *
* Modified 23 Mar 2018, L Schindler, SU  *
*	(Added PTL drivers & Receivers and   *
*	  reduced JJ count)      			 *
* Modified 30 April 2018, L Schindler, SU *
*	(Optimized cell)					 *
* Last mod 9 May 2018, L Schindler, SU   *
*   (Fixed port connections)	         *
******************************************
******************************************
*                 IN_A   IN_B   CLK   OUT
*$Ports             in_A  in_B  in_clk  out_out
.SUBCKT mitll_and2t 29 12 7 19
*==============  Begin SPICE netlist of main design ============
B01        36         40         jmitll     area=1.31899
B01rx1    6          8          jmitll     area=0.901389
B01rx2    11         13         jmitll     area=0.88063
B01rx3    28         30         jmitll     area=0.88063
B01tx1    16         20         jmitll     area=2.26625
B02        63         67         jmitll     area=1.31899
B03        37         48         jmitll     area=1.13403
B04        68         64         jmitll     area=1.13403
B05        49         50         jmitll     area=1.52701
B06        50         69         jmitll     area=1.52701
B07        51         52         jmitll     area=1.25725
B08        43         47         jmitll     area=1.16701
B09        54         55         jmitll     area=2.03545
B10        34         39         jmitll     area=1.75934
B11        61         66         jmitll     area=1.75934
B14        41         46         jmitll     area=1.50181
IB01       0          38         pwl(0      0 5p 0.000113269)
IB01rx1   0          9          pwl(0      0 5p 0.00012754)
IB01rx2   0          14         pwl(0      0 5p 0.000131447)
IB01rx3   0          31         pwl(0      0 5p 0.000131447)
IB01tx1   0          22         pwl(0      0 5p 0.000213665)
IB02       0          65         pwl(0      0 5p 0.000113269)
IB03       0          56         pwl(0      0 5p 6.26758e-005)
IB07       0          45         pwl(0      0 5p 0.000179299)
L01        37         49         2.57965e-012
L01rx1    7          6          1.7746e-012
L01rx2    12         11         1.53695e-012
L01rx3    29         28         1.53695e-012
L01tx1    54         16         4.64399e-012
L02        69         64         2.57965e-012
L02tx1    16         18         2.74282e-012
L03        34         35         1.93254e-012
L04        61         62         1.93254e-012
L05        44         48         1.14641e-012
L06        68         44         1.14641e-012
L07        42         43         1.99319e-012
L08        51         53         3.9e-014  
L09        53         54         2.92475e-012
L13        28         34         2.2304e-012
L14        11         61         2.2304e-012
L15        35         36         6.1049e-012
L16        62         63         6.1049e-012
L17        6          41         1.94279e-012
L19        41         42         2.03734e-013
L20        50         51         3.9901e-013
L21        36         37         1.29089e-013
L22        63         64         1.29089e-013
L23        43         44         1e-014    
LP01       0          40         2.55e-013 
LP01rx1   0          8          3.4e-013  
LP01rx2   0          13         3.4e-013  
LP01rx3   0          30         3.4e-013  
LP01tx1   0          20         5e-014    
LP02       0          67         2.55e-013 
LP07       0          52         2.99e-013 
LP08       0          47         2.11e-013 
LP09       0          55         1.74e-013 
LP10       0          39         2.21e-013 
LP11       0          66         2.21e-013 
LP14       0          46         1.87e-013 
LPR01rx1  6          9          2e-013    
LPR01rx2  11         14         2e-013    
LPR01rx3  28         31         2e-013    
LPR01tx1  16         22         2e-013    
LPR1       35         38         1.3e-014  
LPR2       62         65         1.3e-014  
LPR3       53         56         1.901e-012
LPR4       42         45         8.5e-013  
LRB01      58         0          1e-012    
LRB01rx1  0          10         5e-013    
LRB01rx2  0          15         5e-013    
LRB01rx3  0          32         5e-013    
LRB01tx1  0          21         1e-012    
LRB02      71         0          1e-012    
LRB03      59         48         1e-012    
LRB04      68         72         1e-012    
LRB05      60         50         1e-012    
LRB06      50         75         1e-012    
LRB07      76         0          1e-012    
LRB08      74         0          1e-012    
LRB09      77         0          1e-012    
LRB10      57         0          1e-012    
LRB11      70         0          1e-012    
LRB14      73         0          1e-012    
RB01       58         36         5.20089   
RB01rx1   10         6          7.61037   
RB01rx2   15         11         7.78977   
RB01rx3   32         28         7.78977   
RB01tx1   21         16         3.02698   
RB02       71         63         5.20089   
RB03       59         37         6.04915   
RB04       64         72         6.04915   
RB05       60         49         4.49237   
RB06       69         75         4.49237   
RB07       76         51         5.4563    
RB08       74         43         5.87817   
RB09       77         54         3.37022   
RB10       57         34         3.89913   
RB11       70         61         3.89913   
RB14       73         41         4.56777   
RINStx1   18         19         1.36      
.model jmitll jj(rtype=1, vg=2.6mV, cap=0.07pF, r0=160, rn=16, icrit=0.1mA)
.ends mitll_and2t
*******************************
*******************************
*^^^^^^^^  End of included SPICE model from ./js/mitll_and2t.js ^^^^^^^^
*
*vvvvvvvv  Included SPICE model from ./js/mitll_xort.js vvvvvvvv
*****************************************
* Begin .SUBCKT model                    *
* spice-sdb ver 4.28.2007                *
*                                        *
* RSFQ generic cell for MITLL sfq5ee     *
* Project under IARPA-BAA-16-03          *
* Authored 1 March 2016, JA Delport, SU  *
* Modified 11 Oct 2016, CJ Fourie, SU    *
*   (Added B10, optimized)               *
* Modified 23 Mar 2018, L Schindler, SU  *
*	(Added PTL drivers & Receivers and   *
*	  reduced JJ count)      			 *
* Last mod 30 April 2018, L Schindler, SU *
*	(Optimized cell)					 *
******************************************
*                 IN_A   IN_B   CLK   OUT
*$Ports             in_A  in_B  in_clk  out_out
.SUBCKT mitll_xort 16 59 7 26 
*==============  Begin SPICE netlist of main design ============
B01        43         44         jmitll     area=2.79835
B01rx1     6          11         jmitll     area=0.723632
B01rx2     58         63         jmitll     area=1.21244
B01rx3     15         20         jmitll     area=1.21244
B02rx1     9          10         jmitll     area=0.772041
B02rx2     61         62         jmitll     area=1.15856
B02rx3     18         19         jmitll     area=1.15856
B02tx1     25         27         jmitll     area=1.36946
B03        43         72         jmitll     area=1.91585
B03rx1     34         74         jmitll     area=0.827992
B03rx2     52         78         jmitll     area=0.89775
B03rx3     53         76         jmitll     area=0.89775
B04        41         42         jmitll     area=2.79835
B06        41         70         jmitll     area=1.91585
B07        37         36         jmitll     area=1.48566
B08        38         39         jmitll     area=0.933603
B09        33         40         jmitll     area=1.28591
B10        33         45         jmitll     area=1.6863
IB01       0          51         pwl(0      0 5p 8.9218e-005)
IB01rx1    0          12         pwl(0      0 5p 0.000131858)
IB01rx2    0          64         pwl(0      0 5p 0.000229789)
IB01rx3    0          21         pwl(0      0 5p 0.000229789)
IB02       0          54         pwl(0      0 5p 8.9218e-005)
IB02tx1    0          29         pwl(0      0 5p 6.64568e-005)
IB04       0          73         pwl(0      0 5p 0.000124046)
IB05       0          50         pwl(0      0 5p 0.000177629)
L01rx1     7          6          1.89277e-012
L01rx2     59         58         1.86037e-012
L01rx3     16         15         1.86037e-012
L02rx1     6          8          2.23806e-012
L02rx2     58         60         2.15285e-012
L02rx3     15         17         2.15285e-012
L03        72         71         2.27926e-012
L03rx1     8          9          2.02047e-012
L03rx2     60         61         1.97288e-012
L03rx3     17         18         1.97288e-012
L03tx1     25         24         2.22608e-012
L04rx1     9          34         2.01777e-012
L04rx2     61         52         2.3966e-012
L04rx3     18         53         2.3966e-012
L06        70         71         2.27926e-012
L08        71         36         1.75154e-012
L09        37         38         1.26199e-012
L10        38         40         2.22462e-012
L11        34         33         1.80333e-012
L12        38         25         1.8658e-012
L14        52         43         1.6354e-012
L15        53         41         1.6354e-012
LP01       0          44         2e-013    
LP01rx1    0          11         2e-013    
LP01rx2    0          63         2e-013    
LP01rx3    0          20         2e-013    
LP02rx1    0          10         2e-013    
LP02rx2    0          62         2e-013    
LP02rx3    0          19         2e-013    
LP02tx1    0          27         2e-013    
LP03       0          42         2e-013    
LP03rx1    0          74         2e-013    
LP03rx2    0          78         2e-013    
LP03rx3    0          76         2e-013    
LP05       0          39         2e-013    
LP06       0          45         2e-013    
LPR01      43         51         2e-013    
LPR01rx1   8          12         2e-013    
LPR01rx2   60         64         2e-013    
LPR01rx3   17         21         2e-013    
LPR02      41         54         2e-013    
LPR02tx1   25         29         2e-013    
LPR04      73         71         2e-013    
LPR05      33         50         2e-013    
LRB01      0          47         1e-012    
LRB01rx1   0          13         1e-012    
LRB01rx2   0          65         1e-012    
LRB01rx3   0          22         1e-012    
LRB02rx1   0          14         1e-012    
LRB02rx2   0          66         1e-012    
LRB02rx3   0          23         1e-012    
LRB02tx1   0          28         1e-012    
LRB03      68         72         1e-012    
LRB03rx1   0          75         1e-012    
LRB03rx2   0          79         1e-012    
LRB03rx3   0          77         1e-012    
LRB04      0          48         1e-012    
LRB06      69         70         1e-012    
LRB07      35         37         1e-012    
LRB08      0          49         1e-012    
LRB09      55         33         1e-012    
LRB10      0          46         1e-012    
RB01       47         43         2.45141   
RB01rx1    13         6          9.47982   
RB01rx2    65         58         5.65794   
RB01rx3    22         15         5.65794   
RB02rx1    14         9          8.88542   
RB02rx2    66         61         5.92104   
RB02rx3    23         18         5.92104   
RB02tx1    28         25         5.0092    
RB03       68         43         3.58061   
RB03rx1    75         34         8.28498   
RB03rx2    79         52         7.64122   
RB03rx3    77         53         7.64122   
RB04       48         41         2.45141   
RB06       69         41         3.58061   
RB07       36         35         4.61741   
RB08       49         38         7.34778   
RB09       40         55         5.33469   
RB10       46         33         4.06803   
RINStx1    24         26         1.36      
.model jmitll jj(rtype=1, vg=2.8mV, cap=0.07pF, r0=160, rn=16, icrit=0.1mA)
.ends mitll_xort
*******************************
*^^^^^^^^  End of included SPICE model from ./js/mitll_xort.js ^^^^^^^^
*
*vvvvvvvv  Included SPICE model from ./js/mitll_or2t.js vvvvvvvv
*****************************************
* Begin .SUBCKT model                    *
* spice-sdb ver 4.28.2007                *
*                                        *
* RSFQ generic cell for MITLL sfq5ee     *
* Project under IARPA-BAA-16-03          *
* Authored 1 March 2016, JA Delport, SU  *
* Modified 11 Oct 2016, CJ Fourie, SU    *
*   (Added B10, optimized)               *
* Modified 23 Mar 2018, L Schindler, SU  *
*	(Added PTL drivers & Receivers and   *
*	  reduced JJ count)      			 *
* Last mod 30 April 2018, L Schindler, SU *
*	(Optimized cell)					 *
******************************************
*                 IN_A   IN_B   CLK   OUT
*$Ports             in_A  in_B  in_clk  out_out
.SUBCKT mitll_or2t 62 54 5 16 
*==============  Begin SPICE netlist of main design ============
B01        30         31         jmitll     area=1.43648
B01rx1     4          9          jmitll     area=0.498239
B01rx2     53         55         jmitll     area=0.761009
B01rx3     61         63         jmitll     area=0.761009
B01tx1     13         17         jmitll     area=1.4217
B02        30         34         jmitll     area=1.02669
B02rx1     7          67         jmitll     area=0.709348
B03        32         33         jmitll     area=1.43648
B03rx1     7          8          jmitll     area=0.624715
B04        32         35         jmitll     area=1.02669
B05        36         37         jmitll     area=1.07602
B08        22         23         jmitll     area=1.00901
B09        14         26         jmitll     area=1.78161
B10        48         36         jmitll     area=1.85929
IB01       0          47         pwl(0      0 5p 0.000258575)
IB01rx1    0          10         pwl(0      0 5p 6.19356e-005)
IB01rx2    0          56         pwl(0      0 5p 9.93419e-005)
IB01rx3    0          64         pwl(0      0 5p 9.93419e-005)
IB01tx1    0          19         pwl(0      0 5p 0.000124071)
IB02       0          29         pwl(0      0 5p 4.45911e-005)
IB04       0          50         pwl(0      0 5p 7.34836e-005)
L01        38         30         1.19917e-012
L01rx1     5          4          1.31862e-012
L01rx2     54         53         1.0157e-012
L01rx3     62         61         1.0157e-012
L01tx1     14         13         3.33856e-012
L02        34         39         1.12533e-012
L02rx1     4          6          2.19746e-012
L02rx2     53         40         1.66138e-012
L02rx3     61         38         1.66138e-012
L02tx1     13         15         2.41485e-012
L03        40         32         1.19917e-012
L03rx1     6          7          2.41399e-012
L04        35         39         1.12533e-012
L05        39         41         6e-013    
L06        41         48         2.39701e-012
L07        36         28         4e-013    
L08        28         8          4.37488e-012
L09        8          22         1.60915e-012
L13        22         25         1.86893e-012
L14        25         14         8.12022e-013
LP01       31         0          2e-013    
LP01rx1    0          9          3.4e-013  
LP01rx2    0          55         3.4e-013  
LP01rx3    0          63         3.4e-013  
LP01tx1    0          17         5e-014    
LP02rx1    0          67         3.4e-013  
LP03       33         0          2e-013    
LP05       37         0          2e-013    
LP08       0          23         1.17e-013 
LP09       0          26         1.51e-013 
LPIB01     41         47         2e-013    
LPIB02     28         29         2e-013    
LPIB04     25         50         2e-013    
LPR01rx1   6          10         2e-013    
LPR01rx2   40         56         2e-013    
LPR01rx3   38         64         2e-013    
LPR01tx1   13         19         2e-013    
LRB01      43         0          1e-012    
LRB01rx1   0          11         5e-013    
LRB01rx2   0          57         5e-013    
LRB01rx3   0          65         5e-013    
LRB01tx1   0          18         1e-012    
LRB02      45         34         1e-012    
LRB02rx1   0          68         5e-013    
LRB03      42         0          1e-012    
LRB03rx1   8          12         1e-012    
LRB04      46         35         1e-012    
LRB05      44         0          1e-012    
LRB08      24         0          1e-012    
LRB09      27         0          1e-012    
LRB10      49         36         1e-012    
RB01       30         43         4.7755    
RB01rx1    11         4          13.7683   
RB01rx2    57         53         9.01423   
RB01rx3    65         61         9.01423   
RB01tx1    18         13         4.82513   
RB02       30         45         6.68158   
RB02rx1    68         7          9.67072   
RB03       32         42         4.7755    
RB03rx1    12         7          10.9809   
RB04       32         46         6.68158   
RB05       36         44         6.37527   
RB08       24         22         6.79868   
RB09       27         14         3.8504    
RB10       48         49         3.68953   
RINStx1    15         16         1.36      
.model jmitll jj(rtype=1, vg=2.8mV, cap=0.07pF, r0=160, rn=16, icrit=0.1mA)
.ends mitll_or2t
*******************************
*^^^^^^^^  End of included SPICE model from ./js/mitll_or2t.js ^^^^^^^^
*
*vvvvvvvv  Included SPICE model from ./js/mitll_dfft.js vvvvvvvv
*****************************************
* Begin .SUBCKT model                    *
* spice-sdb ver 4.28.2007                *
*                                        *
* RSFQ generic cell for MITLL sfq5ee     *
* Project under IARPA-BAA-16-03          *
* Authored 5 Nov 2015, CJ Fourie, SU     *
* Modified 1 March 2016, JA Delport, SU  *
* Modified 23 Aug 2016, CJ Fourie, SU    *
* Modified 9 Oct 2016, CJ Fourie, SU     *
*   (added DMP junction B2, optmized)    *
* Modified 23 Mar 2018, L Schindler, SU  *
*	(Added PTL drivers & Receivers and   *
*	  reduced JJ count)      			 *
* Last mod 30 April 2018, L Schindler, SU *
*	(Optimized cell)					 *
******************************************
*					in		clk		out
*$Ports             in_in  in_clk  out_out
.SUBCKT mitll_dfft 9 7 10 
*
*==============  Begin SPICE netlist of main design ============
B01rx1     20         22         jmitll     area=0.793833
B01rx2     12         16         jmitll     area=0.906104
B01tx      26         27         jmitll     area=3.02709
B02rx2     14         15         jmitll     area=0.963766
B1         30         31         jmitll     area=1.42778
B2         39         52         jmitll     area=1.49875
B3         45         51         jmitll     area=0.960227
B4         32         33         jmitll     area=1.6952
B5         43         32         jmitll     area=1.17345
B6         36         37         jmitll     area=1.36404
B7         34         35         jmitll     area=1.49997
IB01rx1    0          23         pwl(0      0 5p 0.000115456)
IB01rx2    0          17         pwl(0      0 5p 0.000101889)
IB01tx     0          29         pwl(0      0 5p 0.000181403)
IB1        0          53         pwl(0      0 5p 0.000120402)
IB2        0          54         pwl(0      0 5p 6.34786e-005)
IB3        0          55         pwl(0      0 5p 0.000153633)
IB4        0          56         pwl(0      0 5p 0.00016173)
L01rx1     9          20         1.40665e-012
L01rx2     7          12         1.23102e-012
L01tx1     26         25         1.80401e-012
L02rx1     20         21         3.29467e-012
L02rx2     12         13         2.44036e-012
L03rx2     13         14         3.64944e-012
L1         21         30         1.12845e-012
L2a        30         48         5.40283e-013
L2b        48         39         1.60289e-012
L3a        45         49         9.45374e-013
L3b        49         32         4.44009e-012
L4         52         45         1.11414e-012
L5a        32         50         3.63494e-012
L5b        50         34         5.93935e-013
L6         34         26         1.32327e-012
L7         36         43         1.9079e-012
L8         14         36         1.79764e-012
LIB01rx2   13         17         2e-013    
LIB01tx    26         29         2e-013    
LIB2       49         54         2e-013    
LIB3       50         55         2e-013    
LPB01rx1   0          22         3.4e-013  
LPB01rx2   0          16         3.4e-013  
LPB01tx    0          27         5e-014    
LPB02rx2   0          15         6e-014    
LPB1       31         0          2e-013    
LPB3       51         0          2e-013    
LPB4       33         0          2e-013    
LPB6       37         0          2e-013    
LPB7       35         0          2e-013    
LPIB01rx1  21         23         2e-013    
LPIB1      48         53         2e-013    
LPIB4      56         36         2e-013    
LRB01rx1   0          24         5e-013    
LRB01rx2   0          18         5e-013    
LRB01tx    0          28         1e-012    
LRB02rx2   0          19         1e-012    
LRB1       41         0          1e-012    
LRB2       38         52         1e-012    
LRB3       44         0          1e-012    
LRB4       46         0          1e-012    
LRB5       42         32         1e-012    
LRB6       40         0          1e-012    
LRB7       47         0          1e-012    
RB01rx1    24         20         8.6415    
RB01rx2    18         12         7.57077   
RB01tx     28         26         2.26617   
RB02rx2    19         14         7.11781   
RB1        30         41         4.80461   
RB2        39         38         4.5771    
RB3        45         44         7.14404   
RB4        32         46         4.04666   
RB5        43         42         5.84592   
RB6        40         36         5.02909   
RB7        34         47         4.57337   
RINStx     25         10         1.36      
.model jmitll jj(rtype=1, vg=2.8mV, cap=0.07pF, r0=160, rn=16, icrit=0.1mA)
.ends mitll_dfft
*******************************
*^^^^^^^^  End of included SPICE model from ./js/mitll_dfft.js ^^^^^^^^
*
*vvvvvvvv  Included SPICE model from ./js/mitll_ptlrx.js vvvvvvvv
******************************************
* Begin .SUBCKT model                    *
* spice-sdb ver 4.28.2007                *
*                                        *
* RSFQ generic cell for MITLL sfq5ee     *
* Seedling project under IARPA-BAA-14-03 *
* Authored 1 March 2016, JA Delport, SU  *
* Last mod 16 Oct 2016, CJ Fourie, SU    *
*   (Optimized)                          *
******************************************
.SUBCKT MITLL_PTLRX 2 6 
*==============  Begin SPICE netlist of main design ============
B01        1          9          jmitll     area=1
B02        4          8          jmitll     area=1
B03        5          7          jmitll     area=1
IB01       0          10         pwl(0      0 5p 155u)
L01        2          1          0.2p      
L02        1          3          4.3p      
L03        3          4          4.6p      
L04        4          5          5.0p      
L05        5          6          2.3p      
LP01       0          9          0.34p     
LP02       0          8          0.06p     
LP03       0          7          0.03p     
LPR01      3          10         0.2p      
LRB01      9          11         0.5p      
LRB02      8          12         1p        
LRB03      7          13         1p        
RB01       11         1          9.7       
RB02       12         4          9.7       
RB03       13         5          9.7       
.model jmitll jj(rtype=1, vg=2.8mV, cap=0.07pF, r0=160ohm, rn=16ohm, icrit=0.1mA)
.ends MITLL_PTLRX
*******************************
*^^^^^^^^  End of included SPICE model from ./js/mitll_ptlrx.js ^^^^^^^^
*
*vvvvvvvv  Included SPICE model from ./js/mitll_splitt.js vvvvvvvv
******************************************
* Begin .SUBCKT model                    *
* spice-sdb ver 4.28.2007                *
*                                        *
* RSFQ generic cell for MITLL sfq5ee     *
* Project under IARPA-BAA-16-03          *
* Authored 3 Nov 2015, CJ Fourie, SU     *
* Modified 8 Nov 2016, CJ Fourie, SU     *
*   (Added TimEx port descriptors)       *
* Modified 23 Mar 2018, L Schindler, SU  *
*	(Added PTL drivers & Receivers and   *
*	  reduced JJ count)      			 *
* Last mod 30 April 2018, L Schindler, SU *
*	(Optimized cell)					 *
******************************************
*                      in out1 out2
*$Ports                in_in  out_out1  out_out2
.SUBCKT MITLL_SPLITT 5 13 36 
*==============  Begin SPICE netlist of main design ============
B01rx2     4          6          jjmitll100 area=1.00704
B01tx1     9          14         jjmitll100 area=1.69932
B01tx2     33         37         jjmitll100 area=1.69932
B1         19         20         jjmitll100 area=1.69597
B2         21         22         jjmitll100 area=1.20951
B3         23         24         jjmitll100 area=1.20951
IB01rx2    0          7          pwl(0      0 5p 0.000134948)
IB01tx1    0          16         pwl(0      0 5p 7.6267e-005)
IB01tx2    0          39         pwl(0      0 5p 7.6267e-005)
IB1        0          31         pwl(0      0 5p 0.000359683)
L01rx2     5          4          2.6757e-013
L02tx1     9          12         9.42532e-012
L02tx2     33         35         9.42532e-012
L1         4          19         1.52585e-012
L2         19         25         2.91538e-012
L3         25         26         4.81369e-013
L4         26         21         1.27164e-012
L5         21         9          3.25722e-012
L6         26         23         1.27164e-012
L7         23         33         3.25722e-012
LP01rx2    0          6          3.4e-013  
LP01tx1    0          14         5e-014    
LP01tx2    0          37         5e-014    
Lp1        20         0          2e-013    
Lp2        22         0          2e-013    
Lp3        24         0          2e-013    
LPIB1      25         31         2e-013    
LPR01rx2   4          7          2e-013    
LPR01tx1   9          16         2e-013    
LPR01tx2   33         39         2e-013    
LRB01rx2   0          8          5e-013    
LRB01tx1   0          15         1e-012    
LRB01tx2   0          38         1e-012    
LRB1       28         0          1e-012    
LRB2       30         0          1e-012    
LRB3       29         0          1e-012    
RB01rx2    8          4          6.81198   
RB01tx1    15         9          4.03684   
RB01tx2    38         33         4.03684   
RB1        19         28         4.04483   
RB2        21         30         5.67164   
RB3        23         29         5.67164   
RINStx1    12         13         1.36      
RINStx2    35         36         1.36      
.model jjmitll100 jj(rtype=1, vg=2.8mV, cap=0.07pF, r0=160, rn=16, icrit=0.1mA)
.ends MITLL_SPLITT
*^^^^^^^^  End of included SPICE model from ./js/mitll_splitt.js ^^^^^^^^
*
*vvvvvvvv  Included SPICE model from ./js/mitll_dcsfq.js vvvvvvvv
*****************************************
* Begin .SUBCKT model                   *
* spice-sdb ver 4.28.2007               *
*                                       * 
* RSFQ generic cell for MITLL sfq5ee    *
* Authored 3 Nov 2015, CJ Fourie, SU    *
*****************************************
.SUBCKT mitll_dcsfq 8 11 
*==============  Begin SPICE netlist of main design ============
B1         1          2          jjmitll100 area=2.25
B2         3          4          jjmitll100 area=2.25
B3         5          6          jjmitll100 area=2.5
IB1        0          2          pwl(0      0 5p 275uA)
IB2        0          5          pwl(0      0 5p 175uA)
L1         8          7          1p        
L2         7          0          3.9p      
L3         7          1          0.6p      
L4         2          3          1.1p      
L5         3          5          4.5p      
L6         5          11         2p        
Lp2        4          0          0.2p      
Lp3        6          0          0.2p      
LRB1       9          2          1p        
LRB2       10         4          1p        
LRB3       12         6          1p        
RB1        1          9          4.31      
RB2        3          10         4.31      
RB3        5          12         3.88      
.model jjmitll100 jj(rtype=1, vg=2.8mV, cap=0.07pF, r0=160, rn=16, icrit=0.1mA)
.ends mitll_dcsfq
*******************************
*^^^^^^^^  End of included SPICE model from ./js/mitll_dcsfq.js ^^^^^^^^
*
*vvvvvvvv  Included SPICE model from ./js/mitll_ptltx.js vvvvvvvv
******************************************
* Begin .SUBCKT model                    *
* spice-sdb ver 4.28.2007                *
*                                        *
* RSFQ generic cell for MITLL sfq5ee     *
* Seedling project under IARPA-BAA-14-03 *
* Authored 1 March 2016, JA Delport, SU  *
* Last mod 16 Oct 2016, CJ Fourie, SU    *
*   (Optimized)                          *
******************************************
.SUBCKT MITLL_PTLTX 1 2 
*==============  Begin SPICE netlist of main design ============
B01        3          7          jmitll     area=2
B02        4          6          jmitll     area=1.62
IB01       0          10         pwl(0      0 5p 230u)
IB02       0          11         pwl(0      0 5p 82u)
L01        1          3          2.5p      
L02        3          4          3.3p      
L03        4          5          0.35p     
LP01       0          7          0.05p     
LP02       0          6          0.12p     
LPR01      3          10         0.2p      
LPR02      4          11         1.3p      
LRB01      7          8          1p        
LRB02      6          9          1p        
RB01       8          3          4.85      
RB02       9          4          6.3       
RINS       5          2          1.36      
.model jmitll jj(rtype=1, vg=2.8mV, cap=0.07pF, r0=160ohm, rn=16ohm, icrit=0.1mA)
.ends MITLL_PTLTX
*******************************
*^^^^^^^^  End of included SPICE model from ./js/mitll_ptltx.js ^^^^^^^^
*
*==============  Begin SPICE netlist of main design ============
Icarryin   0          50         pwl(0      0 170p 0 173p 600u 176p 0 253p 0 256p 600u 259p 0)
Iclk       0          83         pulse(0    600u 1p 2p 2p 1p 50p)
IinA       0          52         pwl(0      0 60p 0 63p 600u 66p 0 260p 0 263p 600u 266p 0)
IinB       0          54         pwl(0      0 160p 0 163p 600u 166p 0 270p 0 273p 600u 276p 0)
Rcarry     60         0          2         
Rsum       59         0          2         
T01        82         0          61         0 LOSSLESS Z0=5 TD=10p
T02        62         0          56         0 LOSSLESS Z0=5 TD=10p
T03        63         0          64         0 LOSSLESS Z0=5 TD=10p
T04        57         0          67         0 LOSSLESS Z0=5 TD=10p
T05        58         0          68         0 LOSSLESS Z0=5 TD=10p
T06        66         0          70         0 LOSSLESS Z0=5 TD=10p
T07        71         0          79         0 LOSSLESS Z0=5 TD=1p
T08        72         0          43         0 LOSSLESS Z0=5 TD=10p
T09        73         0          4          0 LOSSLESS Z0=5 TD=10p
T10        74         0          9          0 LOSSLESS Z0=5 TD=10p
T11        75         0          34         0 LOSSLESS Z0=5 TD=10p
T12        76         0          37         0 LOSSLESS Z0=5 TD=10p
T13        77         0          8          0 LOSSLESS Z0=5 TD=10p
T14        78         0          20         0 LOSSLESS Z0=5 TD=10p
T15        80         0          40         0 LOSSLESS Z0=5 TD=2p
T16        81         0          13         0 LOSSLESS Z0=5 TD=2p
T17        47         0          39         0 LOSSLESS Z0=5 TD=10p
T18        45         0          21         0 LOSSLESS Z0=5 TD=10p
T19        22         0          10         0 LOSSLESS Z0=5 TD=10p
T20        23         0          33         0 LOSSLESS Z0=5 TD=10p
T21        25         0          11         0 LOSSLESS Z0=5 TD=10p
T22        26         0          36         0 LOSSLESS Z0=5 TD=10p
T23        46         0          24         0 LOSSLESS Z0=5 TD=10p
T24        41         0          27         0 LOSSLESS Z0=5 TD=10p
T25        12         0          30         0 LOSSLESS Z0=5 TD=10p
T26        35         0          5          0 LOSSLESS Z0=5 TD=10p
T27        38         0          6          0 LOSSLESS Z0=5 TD=10p
T28        29         0          1          0 LOSSLESS Z0=5 TD=10p
T29        31         0          15         0 LOSSLESS Z0=5 TD=10p
T30        32         0          2          0 LOSSLESS Z0=5 TD=10p
T31        3          0          17         0 LOSSLESS Z0=5 TD=10p
T32        7          0          18         0 LOSSLESS Z0=5 TD=10p
T33        19         0          49         0 LOSSLESS Z0=5 TD=10p
T34        28         0          14         0 LOSSLESS Z0=5 TD=10p
T35        16         0          42         0 LOSSLESS Z0=5 TD=10p
T36        44         0          48         0 LOSSLESS Z0=5 TD=10p
T37        65         0          69         0 LOSSLESS Z0=5 TD=10p
X01        MITLL_SPLITT 21         22         23
X02        MITLL_SPLITT 24         25         26
X03        mitll_xort 10         11         9 12
X04        mitll_xort 14         15         13 16
X05        MITLL_SPLITT 30         31         32
X06        MITLL_SPLITT 27         28         29
X07        mitll_dfft 33         34         35
X08        mitll_dfft 36         37         38
X09        mitll_dfft 39         40         41
X10        mitll_dfft 42         43         44
X11        MITLL_AND2T 1          2          4 3
X12        MITLL_AND2T 5          6          8 7
X13        mitll_or2t 17         18         20 19
X14        MITLL_DCSFQ 50         51        
X15        MITLL_PTLTX 51         47        
X16        MITLL_DCSFQ 52         53        
X17        MITLL_PTLTX 53         45        
X18        MITLL_DCSFQ 54         55        
X19        MITLL_PTLTX 55         46        
X20        MITLL_PTLRX 48         59        
X21        MITLL_PTLRX 49         60        
X22        MITLL_SPLITT 61         62         63
X23        MITLL_SPLITT 56         57         58
X24        MITLL_SPLITT 64         65         66
X25        MITLL_SPLITT 67         71         72
X26        MITLL_SPLITT 68         73         74
X27        MITLL_SPLITT 69         75         76
X28        MITLL_SPLITT 70         77         78
X29        MITLL_SPLITT 79         80         81
X30        MITLL_DCSFQ 83         84        
X31        MITLL_PTLTX 84         82        
.tran 0.25p 500p 0 0.25p
*.print PHASE X07_B01rx2
*.print PHASE X08_B01rx2
*.print PHASE X03_B01rx1
*.print PHASE X09_B01rx2
*.print PHASE X04_B01rx1
*.print PHASE X11_B01rx3
*.print PHASE X12_B01rx3
*.print PHASE X10_B01rx2
*.print PHASE X13_B01rx1
*.print DEVI X01_L01rx2
*.print DEVI X01_L02tx1
*.print DEVI X01_L02tx2
*.print DEVI X04_L01rx3
*.print DEVI X04_L01rx2
*.print DEVI X04_L01rx1
*.print DEVI X04_L03tx1
*.print PHASE X10_B01tx
*.print PHASE X06_B01rx2
*.print PHASE X06_B01tx1
*.print PHASE X06_B01tx2
*.print DEVI X11_L01rx1
*.print PHASE X12_B01rx1
*.print PHASE X12_B01rx2
*.print PHASE X12_B01rx3
*.print PHASE X12_B01tx1
.print DEVI IinA
.print DEVI IinB
.print DEVI Icarryin
.print DEVI Rsum
.print DEVI Rcarry
.end
