*****  xic.exe 4.3.4 Win32 i386 05/14/2018 08:42 GMT

.model jmitll jj
+ rtype     = 1             vg        = 2.8mV         cap       = 0.07pF        
+ r0        = 160           rn        = 16            icrit     = 0.1mA         

.model jjmit jj
+ rtype     = 1             vg        = 2.8mV         cap       = 0.07pF        
+ r0        = 160           rn        = 16            icrit     = 0.1mA         
